name: software-engineering-lab-9
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: djangoAdmin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: djangoDB
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Containers
        run: docker-compose up --build -d

      - name: Execute unit tests
        run: docker exec $(docker-compose ps -q api) python django_project/manage.py test django_project/django_app/tests
        # modify the path if necessary

  docs:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.12 # change to your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # make sure your requirements file is up to date

      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python django_project/manage.py generateschema > docs.json
          # modify the paths if necessary

      - name: Commit and push documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html # modify the paths if necessary
          git commit -m "Updated documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}